version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  run-matlab-tests:    
    machine:
      image: ubuntu-2204:current
    parallelism: 4
    steps:
      - checkout
      - run: circleci tests glob "tests/**/*.m" | circleci tests split --split-by=filesize | awk -F'[\\\\/.]' '{print $(NF-1) "/*"}'
      - run:
          name: Collect and Transform Tests
          command: |
            # Collect tests
            TESTS=$(circleci tests glob "tests/**/*.m" \
                    | circleci tests split --split-by=filesize \
                    | awk -F'[\\/ .]' '{print $(NF-1) "/*"}')
      
            # Display raw TESTS
            echo "=== RAW TESTS ==="
            echo "$TESTS"
            echo
      
            # Transform TESTS using awk
            selectByName=$(eval echo "$TESTS" | awk '{ \
              for(i=1; i<=NF; i++) { \
                gsub(/\047/, "\047\047", $i); \
                printf "\047%s\047", $i, (i==NF ? "" : ", "); \
              } \
            }')
      
            # Display transformed TESTS
            echo "=== AFTER awk transformation ==="
            echo "$selectByName"

      # - matlab/run-tests:
      #     select-by-name: $(circleci tests glob "tests/**/*.m" | circleci tests split | awk -F'[\\\\/.]' '{print $(NF-1) "/*"}')
workflows:
  test:
    jobs:
      - run-matlab-tests
